In [1]:
import os
import codecs
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [2]:
cd drive/My\ Drive/Colab Notebooks/test/

/content/drive/My Drive/Colab Notebooks/test

In [3]:
ls

 database_variable.csv  'order&space.csv'   test.ipynb  'test.ipynb 的副本'

In [4]:
import numpy as np
import pandas as pd
data = pd.read_csv("database_variable.csv")
print(len(data))
data

194892

            id  space_id  people  size  ...  category  weekday  is_holiday  status
0         9615         1      17    12  ...         1        3           0       2
1         9617         1      17    12  ...         1        5           0       2
2         9618         1      17    12  ...         1        6           1       2
3         9616         1      17    12  ...         1        7           1       2
4         9622         1      17    12  ...         1        2           0       2
...        ...       ...     ...   ...  ...       ...      ...         ...     ...
194887   21395         3       6     5  ...         1        4           0       1
194888  192016        24       8     5  ...         1        1           0       2
194889   92438        62      10     5  ...         1        7           1       4
194890   53225        41       9     4  ...         1        2           0       4
194891   79893       104       6     3  ...         1        3           0       4

[194892 rows x 13 columns]

In [6]:
x1 = data[data['status'] == 2]
y1 = np.array([1] * len(x1))
x1

            id  space_id  people  size  ...  category  weekday  is_holiday  status
0         9615         1      17    12  ...         1        3           0       2
1         9617         1      17    12  ...         1        5           0       2
2         9618         1      17    12  ...         1        6           1       2
3         9616         1      17    12  ...         1        7           1       2
4         9622         1      17    12  ...         1        2           0       2
...        ...       ...     ...   ...  ...       ...      ...         ...     ...
194883  186299       125      15    10  ...         1        6           1       2
194884  186297       123       8     9  ...         1        6           1       2
194885  186295       121      14    10  ...         1        6           1       2
194886  186294       122      12    10  ...         1        6           1       2
194888  192016        24       8     5  ...         1        1           0       2

[136955 rows x 13 columns]

In [7]:
x2 = data[data['status'] != 2]
y2 = np.array([0] * len(x2))
print(len(x2))
x2

57937

           id  space_id  people  size  ...  category  weekday  is_holiday  status
228      9710         1      17    12  ...         1        6           1       4
243     10696         3       6     5  ...         1        1           0       4
308      9789         1      17    12  ...         1        7           1       4
309     10768         3       6     5  ...         1        1           0       4
311     10769         3       6     5  ...         1        1           0       4
...       ...       ...     ...   ...  ...       ...      ...         ...     ...
194871  66827        23       2     1  ...         1        2           0       1
194887  21395         3       6     5  ...         1        4           0       1
194889  92438        62      10     5  ...         1        7           1       4
194890  53225        41       9     4  ...         1        2           0       4
194891  79893       104       6     3  ...         1        3           0       4

[57937 rows x 13 columns]

In [8]:
x = pd.concat( [x1, x2], axis=0 )
x

           id  space_id  people  size  ...  category  weekday  is_holiday  status
0        9615         1      17    12  ...         1        3           0       2
1        9617         1      17    12  ...         1        5           0       2
2        9618         1      17    12  ...         1        6           1       2
3        9616         1      17    12  ...         1        7           1       2
4        9622         1      17    12  ...         1        2           0       2
...       ...       ...     ...   ...  ...       ...      ...         ...     ...
194871  66827        23       2     1  ...         1        2           0       1
194887  21395         3       6     5  ...         1        4           0       1
194889  92438        62      10     5  ...         1        7           1       4
194890  53225        41       9     4  ...         1        2           0       4
194891  79893       104       6     3  ...         1        3           0       4

[194892 rows x 13 columns]

In [9]:
y =np.hstack((y1,y2))
y

array([1, 1, 1, ..., 0, 0, 0])

In [10]:
x = x.drop('status', axis = 1)
x

           id  space_id  people  size  ...  zipcode  category  weekday  is_holiday
0        9615         1      17    12  ...    100.0         1        3           0
1        9617         1      17    12  ...    100.0         1        5           0
2        9618         1      17    12  ...    100.0         1        6           1
3        9616         1      17    12  ...    100.0         1        7           1
4        9622         1      17    12  ...    100.0         1        2           0
...       ...       ...     ...   ...  ...      ...       ...      ...         ...
194871  66827        23       2     1  ...    104.0         1        2           0
194887  21395         3       6     5  ...    106.0         1        4           0
194889  92438        62      10     5  ...    105.0         1        7           1
194890  53225        41       9     4  ...    106.0         1        2           0
194891  79893       104       6     3  ...    105.0         1        3           0

[194892 rows x 12 columns]

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, 
                                                    test_size=0.2, 
                                                    random_state=0)

In [12]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression().fit(X_train, y_train)
print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

ValueError: ignored